import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import PrelineScriptWrapper from "@/components/PrelineScriptWrapper";
import Header from "@/components/header/header";

// Import Poppins
const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // bisa pilih weight sesuai kebutuhan
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased overflow-y-scroll`}
      >
         <Header/>
        <PrelineScriptWrapper />
        {children}
      </body>
    </html>
  );
}
